NREL/routee-compass

rust/routee-compass/src/app/compass/compass_app.rs
this PR checks if input plugin processing resulted in 0 queries and returns any error responses if this is the case.
Closes #12.
=> skip chunking if empty

.github/workflows/python-release.yaml
this PR sets the python build operation to only happen when the release's tag begins with the string `py-`. this was tested by creating two releases from two "valid" tags. the build process correctly activated from the `py-` tag and didn't run from the `rs-` tag.
publishing to pypi and crates is done manually; we only use CI to build python wheels for different OSs and python versions, so for this issue, we really only needed to make sure that the python build didn't happen for rust releases.
Closes #6.
=> trigger build on release tag prefix "py-"

docs/notebooks/open_street_maps_example.ipynb, rust/routee-compass-powertrain/src/routee/speed_grade_model.rs
Improves the error for the speed grade model when the energy model provided under the `model_name` parameter cannot be found in the library. When providing the key `"model_name": "flying_car"` for the default OSM energy config produces the error:
> failure building traversal model: No energy model found with name \'flying_car\', try one of: ["2022_Volvo_XC40_Recharge_twin", "2012_Ford_Focus", "2016_TOYOTA_Corolla_4cyl_2WD", "2016_TOYOTA_Highlander_Hybrid", "2016_TESLA_Model_S60_2WD", "2016_AUDI_A3_4cyl_2WD", "2016_CHEVROLET_Spark_EV", "2017_Maruti_Dzire_VDI", "2020_Chevrolet_Colorado_2WD_Diesel", "2016_Toyota_Prius_Two_FWD", "2022_Tesla_Model_3_RWD", "2017_CHEVROLET_Bolt", "2012_Ford_Fusion", "2016_TOYOTA_Camry_4cyl_2WD", "2020_VW_Golf_2.0TDI", "2022_Ford_F-150_Lightning_4WD", …
=> Improve energy model error

python/nrel/routee/compass/resources/osm_default_distance.toml, python/nrel/routee/compass/resources/osm_default_energy.toml, python/nrel/routee/compass/resources/osm_default_speed.toml, rust/routee-compass-core/src/util/unit/distance_unit.rs, rust/routee-compass-core/src/util/unit/energy_rate_unit.rs, rust/routee-compass-core/src/util/unit/energy_unit.rs, rust/routee-compass-core/src/util/unit/grade_unit.rs, rust/routee-compass-core/src/util/unit/speed_unit.rs, rust/routee-compass-core/src/util/unit/time_unit.rs, rust/routee-compass/src/plugin/input/default/rtree/builder.rs, rust/routee-compass/src/plugin/input/default/rtree/plugin.rs, rust/routee-compass/src/plugin/plugin_error.rs
this PR adds optional "distance_tolerance" and "distance_unit" parameters for the rtree plugin. there is no associated issue so i'll describe the problem here.
currently, if the user loads a road network and then submits a query that is well outside of the road network region, the rtree plugin will still find the nearest vertex. this leads to unexpected behavior where matched origins and destinations may be miles from the user-requested locations.
when the nearest vertex is found, if the optional tolerance is provided, the plugin checks that the vertex found does not exceed the distance tolerance from the query coordinate. if the tolerance is exceeded, the query fails. if no tolerance is provided, then we get the original behavior (tolerance is _infinite_).
i have updated the …
=> optional distance tolerance paramter for rtree plugin

rust/routee-compass/src/app/compass/config/config_json_extension.rs
quick fix that changes the error message for `get_config_serde`. the current error message seems like a copy and paste typo, it implies the type is supposed to be _string-parseable_, but it really should be _deserializable_.
=> fix error message

rust/routee-compass/src/app/compass/config/compass_app_builder.rs, rust/routee-compass/src/app/compass/config/compass_configuration_error.rs, rust/routee-compass/src/app/compass/config/termination_model_builder.rs
more small fries fallout from mep-routee work, this time to list the valid module names when reporting an unknown module name error
=> list valid module names with unknown module error

rust/routee-compass/src/app/compass/config/config_json_extension.rs
This PR makes a slight modification to the recursive call when normalizing paths on a configuration file. If an array is encountered, the function only recurses if the element within the array is either a JSON object or JSON array.
Closes #39.
=> only recurse when array element is array or object

mypy.ini, pyproject.toml, python/nrel/routee/compass/compass_app.py, rust/Cargo.toml, rust/routee-compass-py/Cargo.toml, rust/routee-compass-py/src/app_wrapper.rs, rust/routee-compass/Cargo.toml, rust/routee-compass/src/app/compass/compass_app.rs, rust/routee-compass/src/app/compass/compass_app_ops.rs
Takes a pass at #32 by adding a new optional argument `output_file_override` to the `from_config_file` method on the python compass application. This would allow the user to load the application as:
```python
app = CompassApp.from_config_file("my_config.toml:, output_file_override="my_output.json")
```
I also played around with changing the output file after the application has been loaded (see the rust `CompassApp.with_output_directory()` method) but we can roll that back if seems too weird.
Going through this it still feels a bit awkward but I had a hard time finding an elegant way to give a custom config parameter outside of the context of the config file. I'm open to alternatives if you have any ideas.
=> Update output file location

.github/workflows/python-release.yaml, docs/config.md, docs/query.md, pyproject.toml, rust/routee-compass-core/Cargo.toml, rust/routee-compass-powertrain/Cargo.toml, rust/routee-compass-py/Cargo.toml, rust/routee-compass/Cargo.toml
Prepares for a v0.4.0 release by:
- updating the docs with the latest changes
- bumping version of python and rust to 0.4.0
- including the automatic upload of python release artifacts to PyPI (crate.io release is still manual)
=> bump version; doc update; release action

rust/routee-compass/src/app/compass/compass_app.rs
this PR parallelizes the input plugin operations using the same chunking approach as the search/output plugin parallelization. it also adds a progress bar (using mutex for shared access) to the processing:
```
input plugins:   7%|█████████▆                                                       |  155/2204 [00:17<03:56, 8.67it/s]
````
edit: realized i could also add a progress bar for the searches too.
```
input plugins: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2204/2204 [04:24<00:00, 8.33it/s]
[2023-11-30T21:35:39Z INFO  routee_compass::app::compass::compass_app] creating 12 parallel batches across 16 threads to run queries with chunk size 520
search:   2%|██▇ …
```
=> parallelize + show progress for input plugins

rust/routee-compass/src/plugin/input/default/edge_rtree/edge_rtree_record.rs
while working on #58, i discovered i had the wrong understanding of the API for rstar::RTree. it turns out the distance metric should be the _squared euclidean distance_. 
our points are in lat/lon, which is a spherical 2D plane aka non-Euclidean. i would assume a haversine distance formula would produce more accurate values. however, after making this change, a simple test case produced an invalid result.
this PR changes the edge rtree distance function to match the vertex rtree distance function, using the squared Euclidean (lat/lon) distance between points. we can have further discussion in #58 as to whether these should be calculated directly as this is or via some transform for accuracy.
=> switch to Euclidean squared distance

docs/config.md, rust/routee-compass/src/plugin/input/default/load_balancer/custom_weight_type.rs, rust/routee-compass/src/plugin/input/default/load_balancer/mod.rs, rust/routee-compass/src/plugin/input/default/load_balancer/weight_heuristic.rs
this PR is work done under the MEP project that adds a custom load balancing weight heuristic. it is designed for either numeric or categorical fields. this sets me up in the MEP project to load balance in the absence of trip destinations by keying off of the travel modes.
```json
{
"my_weight_value": 3.14159
}
```
```toml
[[plugin.input_plugins]]
type = "load_balancer"
[plugin.input_plugins.weight_heuristic]
type = "custom"
[plugin.input_plugins.weight_heuristic.custom_weight_type]
type = "numeric"
column_name = "my_weight_value"
```
```json
{
"mode": "bike"
}
```
```toml
[[plugin.input_plugins]]
type = "load_balancer"
[plugin.input_plugins.weight_heuristic]
type = "custom"
[plugin.input_plugins.weight_heuristic.custom_weight_type]
type = "categorical"
column_name = "mode"
default = 1 …
```
=> custom load balancing heuristic

rust/routee-compass-core/src/algorithm/search/a_star/a_star_algorithm.rs, rust/routee-compass-core/src/algorithm/search/search_algorithm.rs, rust/routee-compass-core/src/model/frontier/default/no_restriction.rs, rust/routee-compass-core/src/model/frontier/default/road_class.rs, rust/routee-compass-core/src/model/frontier/frontier_model_builder.rs, rust/routee-compass-core/src/model/frontier/frontier_model_error.rs, rust/routee-compass-core/src/model/frontier/frontier_model_service.rs, rust/routee-compass-core/src/model/frontier/mod.rs, rust/routee-compass/src/app/compass/compass_app.rs, rust/routee-compass/src/app/compass/compass_app_error.rs, rust/routee-compass/src/app/compass/config/builders.rs, rust/routee-compass/src/app/compass/config/compass_app_builder.rs, rust/routee-compass/src/app/compass/config/compass_configuration_error.rs, rust/routee-compass/src/app/compass/config/frontier_model/no_restriction_builder.rs, rust/routee-compass/src/app/compass/config/frontier_model/road_class_builder.rs, rust/routee-compass/src/app/search/search_app.rs
this PR done as part of the MEP task sets up FrontierModels to have the same kind of query-time parameterization as TraversalModels do. this will open up frontier rules for MEP queries so that, at query time, we can restrict roadways based on travel mode (walk, bike, drive).
=> parameterize frontier model at query time via service

rust/routee-compass/src/app/compass/config/compass_app_builder.rs, rust/routee-compass/src/plugin/input/default/inject/inject_builder.rs, rust/routee-compass/src/plugin/input/default/inject/inject_format.rs, rust/routee-compass/src/plugin/input/default/inject/inject_plugin.rs, rust/routee-compass/src/plugin/input/default/inject/mod.rs, rust/routee-compass/src/plugin/input/default/mod.rs
this MEP task improvement is so that i can inject something i want to appear in _every_ query for some input file.
i have 12501226 rows of queries covering every US state. i want to keep that dataset small as possible, but i also want to append this hulking JSON value as the `grid_search`: `{"modes":[{"mode":"walk","road_classes":["4","5","6","7"]},{"mode":"bike","road_classes":["4","5","6","7"]},{"mode":"drive","road_classes":["1","2","3","4","5","6"]}]}`.
this plugin allows me to specify some key and value to inject into each input query. usage looks like this:
```toml
[[plugin.input_plugins]]
type = "inject"
key = "grid_search"
value = '{"modes":[{"mode":"walk","road_classes":["4","5","6","7"]},{"mode":"bike","road_classes":["4","5","6","7"]},{"mode":"drive","road_classes":["1","2","3", …
```
=> inject input plugin

rust/routee-compass/src/plugin/output/default/traversal/traversal_ops.rs
a small change here. this function fell out of MEP work and may as well go alongside the create_tree_multilinestring operation.
=> create tree multipoint

rust/routee-compass-powertrain/src/routee/vehicle/default/bev.rs
Removes the addition of the energy offset to the battery electric energy (which can be negative) due to problems with using this approach producing inverted results. With the offset included, we get results that look like this:
<details>
<summary>Query</summary>
```json
{
"model_name": "2017_CHEVROLET_Bolt",
"starting_soc_percent": 100,
"grid_search": {
"energy_cost_coefficient": [
0,
0.2,
0.4,
0.6000000000000001,
0.8,
1
]
},
"destination_y": 39.96400556338435,
"destination_x": -105.09385002667304,
"origin_y": 39.62257436349091,
"origin_x": -104.88747463756835
}
```
</details>
<details>
<summary>Config</summary>
```toml
parallelism = 2
search_orientation = "edge"
[graph]
edge_list_input_file = "data/tomtom_metro_denver_network/edges-compass.csv.gz"
vertex_list_input_file = …
```
=> Pull out energy offset

rust/routee-compass/src/app/compass/compass_app.rs, rust/routee-compass/src/app/compass/config/compass_app_builder.rs, rust/routee-compass/src/app/compass/config/compass_configuration_field.rs, rust/routee-compass/src/app/compass/config/config_json_extension.rs, rust/routee-compass/src/app/compass/config/frontier_model/road_class/road_class_builder.rs, rust/routee-compass/src/app/compass/config/frontier_model/road_class/road_class_service.rs, rust/routee-compass/src/app/compass/config/graph_builder.rs, rust/routee-compass/src/app/compass/config/termination_model_builder.rs, rust/routee-compass/src/app/compass/config/traversal_model/distance_builder.rs, rust/routee-compass/src/app/compass/config/traversal_model/energy_model_builder.rs, rust/routee-compass/src/app/compass/config/traversal_model/energy_model_vehicle_builders.rs, rust/routee-compass/src/app/compass/config/traversal_model/speed_lookup_builder.rs, rust/routee-compass/src/plugin/input/default/edge_rtree/edge_rtree_input_plugin.rs, rust/routee-compass/src/plugin/input/default/edge_rtree/edge_rtree_input_plugin_builder.rs, rust/routee-compass/src/plugin/input/default/inject/inject_builder.rs, rust/routee-compass/src/plugin/input/default/load_balancer/builder.rs, rust/routee-compass/src/plugin/input/default/load_balancer/custom_weight_type.rs, rust/routee-compass/src/plugin/input/default/vertex_rtree/builder.rs, rust/routee-compass/src/plugin/output/default/to_disk/builder.rs, rust/routee-compass/src/plugin/output/default/traversal/builder.rs, rust/routee-compass/src/plugin/output/default/uuid/builder.rs
this PR modified the signature of methods in `config_json_extension.rs` so that string arguments are _references_ and they can be `String` or `str` types. this makes it so cloning of key names is no longer required for using these methods and at the same time, allows `'static str` arguments, which greatly reduces boilerplate for some applications.
Nick - started this work to relax what we can pass as arguments to the JSON getter extensions we have. this
1. removes the need to `.clone()` keys a lot
2. relax the types we can pass as arguments, so that &str and &String arguments are both valid:
```rust
let parent_1 = String::from("iteration termination function");
let x = config.get_config_i64(&"limit", &parent_1);
```
just letting you know about it, it's going to touch a lot of files, just …
=> relax JSON string arg types

python/nrel/routee/compass/resources/osm_default_energy.toml
this itty bitty PR fixes a typo that set the kWh/$ rate at 5 cents instead of 50.
=> kWh cost factor typo

rust/routee-compass-core/src/algorithm/search/a_star/a_star_algorithm.rs, rust/routee-compass-core/src/algorithm/search/search_algorithm.rs, rust/routee-compass-core/src/model/frontier/frontier_model.rs, rust/routee-compass/src/app/compass/compass_app.rs, rust/routee-compass/src/app/compass/config/builders.rs, rust/routee-compass/src/app/compass/config/compass_app_builder.rs, rust/routee-compass/src/app/compass/config/cost_model/cost_model_service.rs, rust/routee-compass/src/app/compass/config/frontier_model/combined/combined_builder.rs, rust/routee-compass/src/app/compass/config/frontier_model/combined/combined_model.rs, rust/routee-compass/src/app/compass/config/frontier_model/combined/combined_service.rs, rust/routee-compass/src/app/compass/config/frontier_model/combined/mod.rs, rust/routee-compass/src/app/compass/config/frontier_model/mod.rs, rust/routee-compass/src/app/compass/config/frontier_model/road_class/road_class_model.rs, rust/routee-compass/src/app/compass/config/frontier_model/turn_restrictions/mod.rs, rust/routee-compass/src/app/compass/config/frontier_model/turn_restrictions/turn_restriction_builder.rs, rust/routee-compass/src/app/compass/config/frontier_model/turn_restrictions/turn_restriction_model.rs, rust/routee-compass/src/app/compass/config/frontier_model/turn_restrictions/turn_restriction_service.rs, rust/routee-compass/src/app/search/search_app.rs, rust/routee-compass/src/plugin/input/default/edge_rtree/edge_rtree_input_plugin_builder.rs, rust/routee-compass/src/plugin/input/default/grid_search/builder.rs, rust/routee-compass/src/plugin/input/default/inject/inject_builder.rs, rust/routee-compass/src/plugin/input/default/load_balancer/builder.rs, rust/routee-compass/src/plugin/input/default/vertex_rtree/builder.rs, rust/routee-compass/src/plugin/output/default/edgeidlist/builder.rs, rust/routee-compass/src/plugin/output/default/summary/builder.rs, rust/routee-compass/src/plugin/output/default/to_disk/builder.rs, rust/routee-compass/src/plugin/output/default/traversal/builder.rs, rust/routee-compass/src/plugin/output/default/uuid/builder.rs
Implements #94 by adding a new turn restriction frontier model which loads a set of edge id tuples that each represent a turn restriction. 
This also adds the ability for multiple frontier models to be provided and iterates over each model, excluding an edge from the search if any of the models result in an invalid frontier.
=> Add turn restrictions

docs/config.md, pyproject.toml, rust/routee-compass-core/Cargo.toml, rust/routee-compass-powertrain/Cargo.toml, rust/routee-compass-powertrain/README.md, rust/routee-compass-py/Cargo.toml, rust/routee-compass/Cargo.toml
After running into [yet another set of build errors](https://github.com/conda-forge/nrel.routee.compass-feedstock/pull/7/checks?check_run_id=20433194404) with the onnx runtime, I'm proposing that we omit it from our default build for the time being since we're not actually using it. We can come back to this and re-visit if we decide that it's valuable to have.
=> Version 0.6.1

python/nrel/routee/compass/compass_app.py, rust/Cargo.toml, rust/routee-compass/Cargo.toml, rust/routee-compass/src/app/compass/compass_app_error.rs, rust/routee-compass/src/app/compass/config/frontier_model/road_class/road_class_parser.rs, rust/routee-compass/src/main.rs, rust/routee-compass/src/plugin/input/default/edge_rtree/edge_rtree_input_plugin.rs, rust/routee-compass/src/plugin/input/input_plugin_ops.rs, rust/routee-compass/src/plugin/plugin_error.rs
A couple of minor updates:
- use indoc to format the multiline error message a little nicer
- pass the query as a mutable reference to the `package_error` function
=> use indoc for error formatting

rust/routee-compass-powertrain/src/routee/energy_traversal_model.rs, rust/routee-compass/src/app/search/search_app.rs
this itty bitty PR feeds the updated state model into the builders for CostModel and FrontierModel instead of using the instance of the state model that does not know about TraversalModel features. flipping this ordering fixes the problem where the cost summary doesn't seem to report cost summaries for all features.
Closes #143 .
=> fix state model update ordering

.github/workflows/deploy-docs.yaml, .gitignore, docs/notebooks/open_street_maps_example.ipynb, python/nrel/routee/compass/io/generate_dataset.py, rust/routee-compass-core/src/model/traversal/default/speed_traversal_model.rs, rust/routee-compass-powertrain/src/routee/energy_traversal_model.rs
Supersedes #131 by merging that notebook with the notebook on the main branch.
Also includes a few fixes found along the way:
- injects distance from the time model until we have a distance model in the scope for the energy traversal model
- fixes the units for the speed coming out of the time model and into the energy model.
=> update example notebook; bugfixes

rust/routee-compass-powertrain/src/routee/energy_model_service.rs, rust/routee-compass-powertrain/src/routee/energy_traversal_model.rs, rust/routee-compass/src/app/compass/config/traversal_model/energy_model_builder.rs
Update the expected key for the incoming energy model grade units to match the existing format. Also makes the grade unit a required attribute so it doesn't default to something unexpected.
=> incoming grade unit required

python/nrel/routee/compass/resources/osm_default_energy.toml
ugh, one more quick fix, forgot to remove the headings file key from the energy model (and, it blows up when the path normalization function tries to normalize it)
=> remove deprecated key

rust/routee-compass/src/app/compass/config.default.toml
Now that traversal models are declaring their state, we should remove the state entry from the default config file.
=> remove default state from config

rust/routee-compass/src/app/compass/compass_app.rs
this quick PR makes it so a `state` section in the TOML is not required. it can still be provided, but is assumed to be an edge case.
=> state in toml is optional

python/nrel/routee/compass/plot/plot_folium.py
Just a small fix to allow the plotting function to take in a multi-linestring object from the resulting route. Even though we do a line merge on all the incoming route geojson objects, it's still possible that the merge will return a multi-linestring (the particular case where I found this was an exit ramp that loops under the highway). This will just plot all the linestrings in a multi-linestring if that's what we get.
=> allow multi line strings for plotting routes

rust/routee-compass/src/app/compass/response/response_output_policy.rs, rust/routee-compass/src/app/compass/response/response_sink.rs
this PR addresses the fact that the line-writing of responses to a file output sink does not have an auto-flush cadence. for a file output policy, the user can now specify an optional `file_flush_rate` which is a positive integer. after writing every `$file_flush_rate` lines, flush will be called on the output buffer. if not specified, flush is called after every row.
=> flush file sink per optional config parameter

rust/routee-compass-core/src/model/cost/cost_aggregation.rs, rust/routee-compass/src/app/compass/config/cost_model/cost_model_builder.rs
ran into this error:
```
Error: CompassConfigurationError(ExpectedFieldForComponent("weights", "cost"))
```
this is because a TOML didn't include a section for cost weights. but, for this server, it was expected that users would always provide these weight values. the CostModelBuilder doesn't allow for optional arguments.
this PR changes that behavior to the opposite extreme, allowing all arguments to be optional. the belief is that the eventual failure is handled downstream in the CostModel::new method, when both TOML and query-time arguments have both been specified.
=> cost attrs in TOML should be optional

rust/routee-compass/src/plugin/input/default/edge_rtree/edge_rtree_input_plugin.rs
this PR addresses the incorrect logic in the edge rtree search, which previously could visit every edge in the graph for degenerative cases where no valid links exist within the tolerance distance.
Closes #180.
=> search termination criteria fix

rust/routee-compass-core/src/model/state/state_error.rs, rust/routee-compass-core/src/model/state/state_feature.rs, rust/routee-compass-core/src/model/state/state_model.rs, rust/routee-compass-powertrain/src/routee/vehicle/default/bev.rs, rust/routee-compass-powertrain/src/routee/vehicle/default/phev.rs, rust/routee-compass/src/app/search/mod.rs, rust/routee-compass/src/app/search/search_app.rs, rust/routee-compass/src/app/search/search_app_ops.rs
This PR gives the user the option to overwrite initial values for state features at query time. the user
- must be overriding an existing state feature by name
- must match the feature type of the existing (if it was a StateFeature::Distance, it should still be that)
- can ovewrite the initial value of the feature (go from 0.0 to 10.0 minutes initial time)
- can also overwrite the enum variant of the unit (go from Kilometers to Meters)
Added issue #185, that would help further protect against invalid overwrites (a percent should still be a percent).
Closes #145.
=> allow query to overwrite state features

rust/routee-compass-core/src/algorithm/search/a_star/a_star_algorithm.rs, rust/routee-compass-core/src/algorithm/search/a_star/bidirectional_a_star_algorithm.rs, rust/routee-compass-core/src/algorithm/search/a_star/mod.rs, rust/routee-compass-core/src/algorithm/search/direction.rs, rust/routee-compass-core/src/algorithm/search/edge_traversal.rs, rust/routee-compass-core/src/algorithm/search/ksp/ksp_single_via_paths.rs, rust/routee-compass-core/src/algorithm/search/ksp/mod.rs, rust/routee-compass-core/src/algorithm/search/ksp/route_similarity_function.rs, rust/routee-compass-core/src/algorithm/search/search_algorithm.rs, rust/routee-compass-core/src/algorithm/search/search_algorithm_result.rs, rust/routee-compass-core/src/model/road_network/graph.rs, rust/routee-compass-core/src/model/termination/termination_model.rs, rust/routee-compass-core/src/model/termination/termination_model_error.rs, rust/routee-compass-core/src/util/priority_queue.rs, rust/routee-compass/src/app/search/search_app.rs
Here is a draft of a ksp algorithm that could possibly work well at national scale. It requires running a bi-directional a* search tree algorithm and then selecting candidate spots from the intersecting vertices from where to join paths from each search. It does this until it can generate $k$ paths meeting some (dis-) similarity threshold.
This _compiles_ but is not correct, but since my parental leave is imminent, I want to surface this in the condition it's in. Planning to wrap it up in the next few days. My current issue is a "search tree is missing linked vertex 413760" error, which may be due to how I'm building the two a* searches (one must be _reverse_-oriented) or how i collect the two routes into a new one.
In order to rule out mapping from edges to vertices, I am simply using …
=> K-Shortest Paths Solver

rust/routee-compass-core/src/model/traversal/default/speed_traversal_model.rs, rust/routee-compass-core/src/util/priority_queue.rs, rust/routee-compass/src/app/cli/cli_args.rs, rust/routee-compass/src/app/compass/config/traversal_model/energy_model_builder.rs
Some small fixes uncovered during a recent debugging session:
- speed traversal model didn't add distance during the state estimation
- adds a test to priority queue to make sure it works properly with reverse costs
- corrects the expected keys for energy time and distance units
- for the CLI app, sets `--chunksize` to only a long argument since the short argument `-c` conflicts with `--config-file`
=> Add distance to state model in SpeedTraversalModel and other small fixes

rust/routee-compass/src/app/compass/config/cost_model/cost_model_builder.rs, rust/routee-compass/src/app/compass/config/cost_model/cost_model_service.rs
Implements #205 by adding a new configuration parameter on the cost model `expect_exact_weights`. If this is set to false, the application will allow extra weights to be passed through, opening up the possibility of doing a grid search over traversal model that have different weights.
=> Allow extra weights in Cost Model

python/nrel/routee/compass/io/utils.py
Found a bug where some grade maps could not be downloaded, for ex Pittsburgh, PA as it had a two digit longitude and the website requires leading 0s in their longitudes < 100
=> usgs using 0 leading numbers in their webpages

python/nrel/routee/compass/io/utils.py
#213 completed
Updated add_grade_to_graph to have a api_key parameter
=> updated add_grade_to_graph to allow users to pass in a google api key

publish_crates.sh, rust/routee-compass-core/Cargo.toml, rust/routee-compass-core/README.md, rust/routee-compass-macros/Cargo.toml, rust/routee-compass-macros/README.md, rust/routee-compass-powertrain/Cargo.toml, rust/routee-compass-powertrain/README.md, rust/routee-compass-py/Cargo.toml, rust/routee-compass-py/README.md, rust/routee-compass/Cargo.toml, rust/routee-compass/README.md
branched this from the py-0.8.0 tag and updated version references to 0.8.0 in the rust crates in order to release on crates.io as v0.8.0.
=> release 0.8.0 (rust)

python/nrel/routee/compass/io/generate_dataset.py, python/nrel/routee/compass/io/utils.py
In reference to #202:
Previously, generate_dataset would calculate the arrival heading using the preset osmnx `.bearing` method, while departure headings were set to `None`. 
This PR adds two functions written by @nreinicke:
1. `calculate_bearings`, which passes in linestrings and determines what to do with the coordinates based on the number of lat lon pairs
2. `compass_heading`, which calculates a compass bearing based on two lat lon pairs
These functions replace the osmnx method used previously, rather than using osmnx for arrival and the functions for departure. Both headings are added to the same data frame and output to edges-headings-enumerated.csv
=> Add departure headings calculation

rust/Cargo.toml, rust/routee-compass-core/src/model/state/state_model.rs, rust/routee-compass/src/plugin/input/default/grid_search/plugin.rs
this PR refactors the `route.state_model` output field in order to make it clearer to the user how it relates to state tuples.
there were two ways to improve readability, with problems each:
- keep state_model a JSON object, but add an "index" field to denote the tuple index for the feature
- problem: order is not guaranteed, so, programmatically `.zip()`-ing the state tuple with the state_model doesn't give you what you would expect
- change state_model to a JSON array so it structurally matches the state tuple
- problem: we can no longer index into the state model by name: `route.state_model.energy` is no longer a key
i opted for an __array__ because i think programmatic access is probably more useful for people toying around in the JSON outputs. but, this means any existing scripting …
=> serialize state model with index

rust/routee-compass-macros/src/lib.rs
Fixes some pyo3 deprecation warnings that resulted from the latest version bump up to v0.22.2
=> Add pyo3 signature for pybinding functions with optional arguments

rust/routee-compass/src/plugin/input/default/debug/debug_plugin.rs
in the process of using routee incorrectly (sigh) i realized that the debug plugin could fail if the value passed to it was not JSON deserializable. instead of raising that serde_json::Error, i have the debug plugin write a pretty-printed error message in the debug log instead.
not tested, but, since debug is not in the critical path of Compass, we could probably accept this.
=> log to_string_pretty error in debug instead of fail

.github/workflows/python-release.yaml, pyproject.toml, rust/routee-compass-core/Cargo.toml, rust/routee-compass-core/README.md, rust/routee-compass-macros/Cargo.toml, rust/routee-compass-macros/README.md, rust/routee-compass-powertrain/Cargo.toml, rust/routee-compass-powertrain/README.md, rust/routee-compass-py/Cargo.toml, rust/routee-compass-py/README.md, rust/routee-compass/Cargo.toml, rust/routee-compass/README.md, rust/routee-compass/src/doc.md
here's a proposed stopping point for calling it "0.9.0" for Rust.
...should i bump the python versions too?
=> rust bump version minor

rust/routee-compass-core/src/model/unit/energy_rate_unit.rs, rust/routee-compass-core/src/model/unit/energy_unit.rs
The PR is the implementation for https://github.com/NREL/routee-compass/issues/242
I have incorporated the following changes:
1. Update the `enum EnergyRateUnit` with additional SI units:
```
- LitersGasolinePerKilometer
- LitersDieselPerKilometer
- LitersGasolinePerMeter
- LitersDieselPerMeter
```
2. Update the `enum EnergyUnit` with
```
- LitersGasoline
- LitersDiesel
```
4. Updated the implementation for both `EnergyRateUnit` and `EnergyUnit`
- Calculation for match arms of Energy Units have been highlighted in the comment.
Executed the following commands: `cargo build --release` & `cargo test`
<details><summary>Detailed execution of the commands: Both executed successfully </summary>
<p>
```
(routee-compass) ashrest2-41625s:rust ashrest2$ cargo build --release
Compiling …
```
=> Add more energy rate distance units

rust/routee-compass-core/src/algorithm/search/a_star/a_star_algorithm.rs, rust/routee-compass-core/src/model/unit/speed_unit.rs, rust/routee-compass-powertrain/src/model/bev_energy_model.rs, rust/routee-compass-powertrain/src/model/phev_energy_model.rs, rust/routee-compass/src/plugin/output/default/traversal/plugin.rs, rust/routee-compass/src/plugin/output/default/traversal/traversal_ops.rs, rust/routee-compass/src/plugin/output/default/traversal/traversal_output_format.rs
added some improvements here to route + tree serialization so they now serialize using the state model and cost model to add those sections to each link in a route or tree, like this:
```json
"properties": {
"traversal": {
"edge_id": 7563,
"access_cost": 0.008333333384705321,
"traversal_cost": 0.05487432604079934,
"result_state": [
0.2613151025581488,
0.10974865208159863,
0.6234684593965638,
0.06473915841810438,
0.01360034135298995,
99.89210140263648,
48.3,
0.0,
0.05489683033149421
]
},
"state": {
"trip_time": 0.6234684593965638,
"trip_energy": 0.06473915841810438,
"trip_soc": 99.89210140263648,
"trip_distance": 0.2613151025581488
},
"cost": {
"total_cost": 0.4906643208840419,
"trip_energy": 0.007768699010172525,
"trip_distance": 0.17116139217558748,
"trip_time": 0.3117342296982819
}
``` …
=> more complete serialization of state and cost at each route/tree branch

rust/routee-compass-core/src/model/traversal/default/time/mod.rs, rust/routee-compass-core/src/model/traversal/default/time/time_traversal_builder.rs, rust/routee-compass-core/src/model/traversal/default/time/time_traversal_model.rs
i discovered that the TimeTraveresalModel cannot be constructed outside of using a `TimeTraversalBuilder` build method, and this PR simply
- gives it a new method to build from a TimeUnit
- gives it a From method to build from a TimeConfiguration
- makes TimeConfiguration public
- makes the TimeTraversalModel::time_unit struct public
=> open constructors for TimeTraversalModel

docs/examples/01_open_street_maps_example.py, python/nrel/routee/compass/io/utils.py, python/nrel/routee/compass/resources/osm_default_energy_all_vehicles.toml, rust/routee-compass-powertrain/src/model/prediction/interpolation/interpolation_model.rs
There are cases when we need to download just one raster tile for a location and if we pass a list of length one to osmnx, this breaks when it tries to create a virtual raster file. To fix this, we just pass the filepath directly if there is only one tile to use.
Also fixes some mistakes in the default osm config file with all vehicles.
=> fix the add grade step for cases with only one elevation tile

python/nrel/routee/compass/resources/downtown_denver_example/osm_default_energy.toml, python/nrel/routee/compass/resources/osm_default_energy.toml, python/nrel/routee/compass/resources/osm_default_energy_all_vehicles.toml, rust/routee-compass-core/src/model/traversal/default/elevation/elevation_traversal_model.rs, rust/routee-compass-core/src/model/traversal/default/grade/grade_configuration.rs, rust/routee-compass-core/src/model/traversal/default/grade/grade_traversal_engine.rs
When testing the elevation traversal model I was finding that the elevation gain and loss was always zero. This applies some minor fixes to get the trip elevation working:
- update the grade input file key (it was just giving zero grades since the input path wasn't found)
- update trip elevation loss to be distance base rather than grade based
I also made the grade model input required since it would prevent this silent error in the future. 
Lastly, this sets up our default energy configs to use the elevation traversal model
=> minor fixes to elevation traversal model

.github/workflows/rust-bench.yaml, rust/routee-compass/Cargo.toml, rust/routee-compass/benches/README.md, rust/routee-compass/benches/denver_bench.rs
Create a simple benchmark case suggested in #336 and create CI benchmarking workflow.
After the last discussion with @robfitzgerald, we might need to switch `secrets.GITHUB_TOKEN` to a different name.
closes #336
=> Benchmark CI

.github/workflows/rust-bench.yaml
`output.txt` is created in the `./rust` working directory, so this PR specifies the correct output file path.
=> fix failing GA

.github/workflows/rust-bench.yaml, rust/routee-compass/Cargo.toml, rust/routee-compass/benches/README.md, rust/routee-compass/benches/denver_bench.rs
Instead of using `cargo criterion`, which fails due to our progress bars,  I switched to `cargo bench` with the added `--output-format bencher` argument. As noted on the [criterion docs](https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options) as well as this [rust issue](https://github.com/rust-lang/rust/issues/47241#issuecomment-1462725509), I had to either specify the benchmark test or disable benchmark building in the `Cargo.toml`. I was not sure which option to go with, so I decided to modify the `Cargo.toml` to save us from having to edit the GitHub actions command if we ever create more benchmark files, but please let me know if you have different opinions. The drawback of disabling bench building in …
=> fix: switch benchmark running tool

rust/routee-compass-core/src/model/traversal/default/speed/speed_traversal_service.rs, rust/routee-compass-powertrain/src/model/prediction/prediction_model_record.rs, rust/routee-compass/benches/denver_bench.rs, rust/routee-compass/src/app/compass/compass_app.rs, rust/routee-compass/src/app/compass/model/frontier_model/vehicle_restrictions/vehicle_parameter_config.rs, rust/routee-compass/src/app/compass/response/internal_writer.rs, rust/routee-compass/src/app/compass/response/mod.rs, rust/routee-compass/src/app/compass/response/response_output_policy.rs, rust/routee-compass/src/app/compass/response/response_sink.rs, rust/routee-compass/src/app/compass/response/write_mode.rs
In order to reduce the size of the output, it will be compressed using `flate2` if the filename ends in `.gz`. Since `GzEncoder<File>` implements `Write`, most of the code can still be used. The primary challenge of using `GzEncoder` instead of `File` is that the former needs a call to `finish()` when the writing is done. Therefore, my solution implements the `InternalWriter` enum which wraps `File` and `GzEncoder` and implements `finish`. `ResponseSink` now receives an `Arc<Mutex<InternalWriter>>` and calls `finish` in the `close` method.
One important caveat with this solution is that after calling `finish` on `InternalWriter::GzippedFile`, subsequent write attempts will panic. This is due to `GzEncoder<File>::try_finish()`, yet I couldn't find a way to use `GzEncoder<File>::finish()` …
=> Implemented option to return a compressed file when the provided filename ends in `.gz`

rust/routee-compass-powertrain/Cargo.toml
this PR holds the smartcore library dependency at exactly "=0.4.0". out-of-the-blue, dependency resolution for smartcore = "0.4.0" was found to install version 0.4.2 and that version has a breaking change on working with our serialized powertrain models, leading to [this CI failure](https://github.com/NREL/routee-compass/pull/365#issuecomment-3109955567) and failure to compile any version of compass not locked to 0.4.0.
=> hold smartcore at =0.4.0

python/nrel/routee/compass/resources/osm_default_energy.toml, python/nrel/routee/compass/resources/osm_default_energy_all_vehicles.toml, rust/routee-compass-core/src/model/unit/energy_rate_unit.rs
A tiny fix to correct how we were de-serializing the energy rate unit "gallons diesel/mile".
Also proposes adding the battery frontier model as default behavior.
=> Fix diesel unit deserialization
